name: Issue Assignment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  handle_issue_comment:
    runs-on: ubuntu-latest
    steps:
    - name: Calling our deployed API
      run: |
        curl -X POST "https://kdb-bot.vercel.app/api/webhook" \
        --data-binary @"${{ github.event_path }}"

